### ISSUE TITLE
JSon data structures don't own their strings

### ISSUE THREAD

**Issue by simonferquel** [deislabs/libcnab-rust#5]
This allows zero-copy json parsing, at the cost of complexifying the lifetime handling, and not being able to parse from a stream (as the json string from which the string slices are borrowed must outlive the deserialized structure), thus making Bundle::from_file currently not buildable.

I guess we must choose either to
- support loading from a stream (thus making the Bundle and substructures own their strings)
- only support the from_string with constraints on the source string lifetime.

**Comment by simonferquel** [comment]
(for ease of use purpose, I suggest we peak the "Bundle owns its strings" approach)

**Comment by technosophos** [comment]
This was introduced by #4. Here's the error that I get:

```
 cargo test
   Compiling libcnab v0.1.0 (/home/technosophos/Code/Rust/libcnab)
error[E0308]: mismatched types
  --> src/cnab.rs:68:27
   |
68 |         let res: Bundle = serde_json::from_reader(file)?;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `serde::Deserialize<'de>`
              found type `serde::Deserialize<'_>`

error[E0308]: mismatched types
  --> src/cnab.rs:68:27
   |
68 |         let res: Bundle = serde_json::from_reader(file)?;
   |                           ^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `serde::Deserialize<'de>`
              found type `serde::Deserialize<'_>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `libcnab`.
warning: build failed, waiting for other jobs to finish...
error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `libcnab`.

To learn more, run the command again with --verbose.
```

I haven't figured out a work-around for the error above that doesn't involve reading the file into a string and calling the string parser.

**Comment by simonferquel** [comment]
It is completely expected, as explained in https://serde.rs/lifetimes.html:
Basically, serde deserializer can deserialize both structures owning their data, or structures borrowing their data.
We can work with this example:
```rust
#[derive(Serialize, Deserialize)]
struct OwningObject{
  value: String
}

#[derive(Serialize, Deserialize)]
struct BorrowingObject<'a>{
  value: &'a str
}
```
Note that the second structure requires a lifetime annotation that says, as long as BorrowingObject lives, the reference "value" must be valid.

with a json payload like
```json
{
  "value": "Hello world"
}
```

When deserializing into `OwningObject`, serde actually create a copy of the string "Hello world" owned by the result structure.
When deserializing into `BorrowingObject`, serde actually creates a slice reference pointing to the input stream (thus avoiding the allocation/string copy). This is very powerfull, but it requires that the input string outlives the deserialized object. As an exemple this code: 
```rust
let mut obj: BorrowingObject;
{
  let json = getJson();
  obj = serde_json::from_string(json);
}
```
wont compile: `obj` outlives `json`. But
```rust
let mut obj: OwningObject;
{
  let json = getJson();
  obj = serde_json::from_string(json);
}
```
will compile just fine because OwningObject owns its own copy of the "Hello world" string.
As `from_reader` actually takes a stream as input (which discards data as soon as it is consumed), it can't be used with structures borrowing their data.

Note: there is one special case:
Imagine a json payload like:
```json
{
  "value": "Hello \"World\""
}
```
(the thing to note is the use of escape characters in the string)
How does serde support this with borrowing objects? The answer is that in this case it creates an unescaped copy): When you dervice the trait `Deserialize` on a borrowing struct, serde automatically adds a field `scratch: vec<u8>` in your structure. When the deserializer find a string containing an escape char, it decodes it and hold it in this scratch area and the reference points to a slice within this scratch area instead of from the input string.

**Comment by simonferquel** [comment]
I lack some experience with rust code bases but my guess is that for a general purpose library allowing to manipulate data-structures, modify them, reserialize them etc, it would be much more practical to have structures owning their data.

**Comment by technosophos** [comment]
For the bundle reader, I tried several work-arounds last night, but ended up with nothing that felt "natural" -- mostly because of what you said above. The bottom line for me, at this point, is that I don't have enough Rust experience to effectively construct the library around the zero-copy version. So even in terms of being able to maintain a comfortable API, I think we should switch back.

**Comment by technosophos** [comment]
@rylev We're collectively stuck on one of the details with the lifetime system (a PR that got merged the same day as yours). If you have time, could you take a look and weigh in?

**Comment by rylev** [comment]
@technosophos @simonferquel sorry for the delay in the  response. You're both totally right that this does limit what the serializer's can do since the data from which you're serializing must be fully present for the entire lifetime of the bundle. If we think this complicates matters, I'm more than happy to switch back to owned strings.

**Comment by simonferquel** [comment]
@rylev I think it makes sense to revert. Not only because it is more practical, but also because we'll want to introduce things that require mutations of part of the bundles (adding methods to add actions, parameters, etc.). It would also simplify a lot things like creating a bundle from code, without having the calling code to keep source of field values for the whole lifetime of the bundle.

**Comment by rylev** [comment]
Sounds good. I'll make the change. Sorry for making more work for people. I hope we at least got a better understanding of the data needs

**Comment by rylev** [comment]
@simonferquel @technosophos PR is ready. Apologies again. Didn't mean to slow you down or cause a bunch of extra work.
